version: '3.4'

services:
  debug:
    image: app-debug
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file: .env
    command: npm run debug
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - $PWD:/home/user/app
    working_dir: /home/user/app
    networks:
      - debug_network
networks:
  debug_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.93.0.0/16
