version: '3.4'

services:
  dev:
    image: app-dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file: .env
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - $PWD:/home/user/app
    working_dir: /home/user/app
    networks:
      - dev_network
networks:
  dev_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.92.0.0/16
