version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
    volumes:
      - $PWD:/home/user/app
    working_dir: /home/user/app
    networks:
      - private_network
networks:
  private_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.92.0.0/16
